<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="22462" started-at="2019-10-07T21:31:03 IST" finished-at="2019-10-07T21:31:25 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="22462" started-at="2019-10-07T21:31:03 IST" finished-at="2019-10-07T21:31:25 IST">
      <class name="com.konakart.script.KonaKartScriptScenarioFirst">
        <test-method status="PASS" signature="configSetup()[pri:0, instance:com.konakart.script.KonaKartScriptScenarioFirst@56aac163]" name="configSetup" is-config="true" duration-ms="18005" started-at="2019-10-07T21:31:03 IST" finished-at="2019-10-07T21:31:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configSetup -->
        <test-method status="SKIP" signature="positiveScenario(java.lang.String, java.lang.String)[pri:1, instance:com.konakart.script.KonaKartScriptScenarioFirst@56aac163]" name="positiveScenario" duration-ms="0" started-at="2019-10-07T21:31:22 IST" data-provider="testdata" finished-at="2019-10-07T21:31:22 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
at com.konakart.util.ProviderData.provideData(ProviderData.java:49)
at com.konakart.dataprovider.DataProviderData.getDataOne(DataProviderData.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveScenario -->
        <test-method status="PASS" signature="negativeScenario(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.konakart.script.KonaKartScriptScenarioFirst@56aac163]" name="negativeScenario" duration-ms="3396" started-at="2019-10-07T21:31:22 IST" data-provider="testdatasecond" finished-at="2019-10-07T21:31:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Games]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wwww]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[There are no available products.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeScenario -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.konakart.script.KonaKartScriptScenarioFirst@56aac163]" name="endReport" is-config="true" duration-ms="801" started-at="2019-10-07T21:31:25 IST" finished-at="2019-10-07T21:31:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.konakart.script.KonaKartScriptScenarioFirst -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
